apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 060284946135.dkr.ecr.us-east-1.amazonaws.com/myapp-repo:latest
        ports:
        - containerPort: 5000
